### PR TITLE
fix(framework): allow emojis in button util

### LINKED ISSUE #1155: bug(freamework): `createButton` is missing the emoji property
`createButton` only accepts:

```ts
{
    customId?: string | undefined;
    disabled?: boolean | undefined;
    label: string;
    style?: ButtonStyle | undefined;
    url?: string | undefined;
}
```

### PR DESCRIPTION
**Pull request by JPBM135**
Closes #1155

### CODE REVIEW

File: packages/framework/src/components/button.ts [hunk 1]
```diff
@@ -14,6 +15,7 @@ export function createButton({
 }: {
```
Comment (JPBM135) [inline packages/framework/src/components/button.ts:15]:
```suggestion
	emoji,
}: {
```

**Review by almostSouji — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]
