### PR TITLE
fix(cases): reference case

### LINKED ISSUE #1153: bug(websocket): backoff returns ms but it is treated as seconds
## Where?

https://github.com/Naval-Base/yuudachi/blob/main/packages/yuudachi/src/websocket/WebSocketConnection.ts#L89-L114

The logger calls it seconds, but the backoff is configured to return ms.

## Alternatives?

- Return seconds from back-off and multiply in the `setTimeout`
- Divide and round in the logger
- Change the logger verbose to ms

### LINKED ISSUE #1157: bug(reference): error shows object Object instead of case number
https://github.com/Naval-Base/yuudachi/blob/d14681aa88e7fb3acaae24554615dd4a1b60a25c/packages/yuudachi/src/commands/moderation/reference.ts#L34

`args.case` refers to the subcommand, not the (number) argument here:

image

needs to use the case number (first option of subcmd) instead.
(scope includes a check for other instances of this or similar misshandling)

### PR DESCRIPTION
**Pull request by JPBM135**
Closes #1157

### CODE REVIEW

File: packages/yuudachi/src/commands/moderation/reference.ts [hunk 1]
```diff
@@ -31,7 +31,7 @@ export default class extends Command<typeof ReferenceCommand> {
 		const originalCase = await getCase(interaction.guildId, caseId);
 
 		if (!originalCase) {
-			throw new Error(i18next.t("command.mod.common.errors.no_case", { case: args.case, lng: locale }));
+			throw new Error(i18next.t("command.mod.common.errors.no_case", { case: args.case.case, lng: locale }));
```
Comment (appellation) [inline packages/yuudachi/src/commands/moderation/reference.ts:34]: Case ID is already calculated above on line 20; should we just reuse that here?

Comment (JPBM135) [reply packages/yuudachi/src/commands/moderation/reference.ts:34]: Sure, why not

Comment (JPBM135) [reply packages/yuudachi/src/commands/moderation/reference.ts]: Changed in 27eb9c0

**Review by appellation — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]
